import assert from "node:assert/strict";
import { createMockWorkspaceBootstrap } from "./mockData";
import { createWorkspaceState, workspaceReducer, type WorkspaceAction } from "./workspaceReducer";
import { canConfirmBatchRename, type RenameTarget } from "./batchRenameState";
import type { BatchRenamePreview, BatchRenameSession } from "../../app/batchRename";
import type { OperationTaskSnapshot } from "../../app/types";

let state = createWorkspaceState(createMockWorkspaceBootstrap("tauri"));
const target: RenameTarget = { panelId: "panel-1", tabId: "tab", rootPath: "C:\\files", selectionRevision: 0, source: "shortcut", entries: [] };
const send = (action: WorkspaceAction) => { state = workspaceReducer(state, action); };
const session: BatchRenameSession = { sessionId: "session", frozenAt: "2026-09-12T12:00:00+08:00", items: [] };
const preview: BatchRenamePreview = { sessionId: "session", revision: 2, expression: "New-*", previewId: "p", items: [],
  diagnostics: [], changedCount: 2, canApply: true };
send({ type: "batchRenameOpened", payload: { id: "open", target, history: ["last"] } });
assert.equal(state.batchRename?.phase, "loading");
assert.equal(state.batchRename?.expression, "*");
send({ type: "batchRenameSessionLoaded", payload: { id: "open", session } });
send({ type: "batchRenameExpressionChanged", payload: { id: "open", expression: "New-*", revision: 2 } });
send({ type: "batchRenamePreviewReceived", payload: { id: "open", preview } });
assert.ok(canConfirmBatchRename(state.batchRename!));
send({ type: "batchRenameExpressionChanged", payload: { id: "open", expression: "Invalid", revision: 3 } });
assert.equal(canConfirmBatchRename(state.batchRename!), false, "editing immediately invalidates confirmation");
send({ type: "batchRenamePreviewReceived", payload: { id: "open", preview } });
assert.equal(state.batchRename?.preview, undefined, "late preview cannot restore an obsolete plan");
send({ type: "batchRenamePreviewReceived", payload: { id: "open", preview: { ...preview, revision: 3, expression: "Invalid" } } });
send({ type: "batchRenameApplyStarted", payload: { id: "open", requestId: "apply" } });
assert.equal(state.batchRename?.phase, "submitting");
send({ type: "batchRenameExpressionChanged", payload: { id: "open", expression: "too late", revision: 4 } });
assert.equal(state.batchRename?.expression, "Invalid");
const task = { taskId: "task", requestId: "apply", status: "running", sequence: 4 } as OperationTaskSnapshot;
send({ type: "batchRenameTaskReceived", payload: { id: "open", task } });
send({ type: "batchRenameCancelling", payload: { id: "open" } });
send({ type: "batchRenameTaskReceived", payload: { id: "open", task: { ...task, sequence: 3 } } });
assert.equal(state.batchRename?.phase, "cancelling");
send({ type: "batchRenameTaskReceived", payload: { id: "open", task: { ...task, sequence: 6, status: "cancelled" } } });
assert.equal(state.batchRename?.phase, "finished");
send({ type: "batchRenameClosed", payload: { id: "open" } });
send({ type: "batchRenameOpened", payload: { id: "new", target, history: [] } });
send({ type: "batchRenameSessionLoaded", payload: { id: "open", session } });
send({ type: "batchRenameTaskReceived", payload: { id: "open", task } });
send({ type: "batchRenameFailed", payload: { id: "open", message: "late error" } });
assert.equal(state.batchRename?.id, "new");
assert.equal(state.batchRename?.phase, "loading");
assert.equal(state.batchRename?.session, undefined);
console.log("ok - batch dialog invalidates previews and fences old sessions, tasks and edits during execution");
